### PR TITLE
Fix _run_meta_interp method and format several source files

### PR DESCRIPTION
**Pull request by 3tty0n**
This PR fixes the broken JIT test that is defined in `tests/jit.py`.

### CODE REVIEW

**Review by smarr — APPROVED** [review]
Ah, yeah, that's not tested.

Thanks for the fix!

**Comment by 3tty0n** [comment]
@smarr Thanks for your review! 

Should I fix the CI failure? This failure is not caused by different parts I didn't modify.

**Comment by 3tty0n** [comment]
I applied source code format to several files; I changed the title of this PR.

**Comment by smarr** [comment]
There were some updates to PyLint, which I now took care off.

Thanks for the fix!

**Comment by 3tty0n** [comment]
Thank you for your review and for fixing the error caused by the new version of PyLint!

**Pull request merged**
